
tasks:
  - init: |
      pip install cassandra-driver && docker-compose pull 
  - command: |
      docker-compose up

ports:
  - port: 9042
    onOpen: ignore


vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers